### ISSUE TITLE
кочерга гниёт

### ISSUE THREAD

**Issue by Smok1e** [LaineZ/buttex-storage-online-client#2]
# загашники бурлят

![Screenshot_2024-05-09-02-01-18-62_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/LaineZ/buttex-storage-online-client/assets/33802666/ff82d91e-73a7-4257-8fb3-47e91e1ecc51)

**Comment by LaineZ** [comment]
загашник бурлит только в браузере шторм, в Mozilla FIREWORKS такой проблемы нет
![изображение](https://github.com/LaineZ/buttex-storage-online-client/assets/19235522/424653f1-2145-4886-867b-21aadb612608)

![изображение](https://github.com/LaineZ/buttex-storage-online-client/assets/19235522/4e78abb1-465e-4a81-b599-5499b47efe82)
необходимо дополнительное расследование

**Comment by LaineZ** [comment]
Пофикшено, надо было пару кссок добавить
